### ISSUE TITLE
Периодический запрос обновления прошивки

### ISSUE THREAD

**Issue by DevNulPavel** [ilya-fedin/autoflash#2]
Добрый день.

Не подскажете, периодически происходит редирект на web интерфейс модема в браузере с предложением обновить прошивку, хотя при этом галочки автоматического обновления везде отключены в модеме. 

Могу ли я как-то это исправить, например через telnet?

**Comment by ilya-fedin** [comment]
Я уже не помню :thinking: 
Помню, в постах rust3028 в теме e3372 на 4pda было что-то по этому поводу.

**Comment by DevNulPavel** [comment]
Спасибо, посмотрю

**Comment by DevNulPavel** [comment]
Напишу сюда на всякий пожарный то, что нашел

https://4pda.ru/forum/index.php?showtopic=582284&st=39300#entry75080197
https://4pda.ru/forum/index.php?showtopic=582284&st=52040#entry90542120
https://4pda.ru/forum/index.php?showtopic=582284&st=45720#entry83800575
